using Xunit;

namespace TestProject
{
	public class Faker	{
		[Fact]
		public void RefreshPlugins()
		{
			Assert.True(false, "autogenerated");
		}
		
		[Fact]
		public void isDTO()
		{
			Assert.True(false, "autogenerated");
		}
		
		[Fact]
		public void GenerateParametersForConstructor()
		{
			Assert.True(false, "autogenerated");
		}
		
		[Fact]
		public void GenerateFields()
		{
			Assert.True(false, "autogenerated");
		}
		
		[Fact]
		public void GenerateDTO()
		{
			Assert.True(false, "autogenerated");
		}
		
		[Fact]
		public void CreateInner()
		{
			Assert.True(false, "autogenerated");
		}
		
		[Fact]
		public void Create()
		{
			Assert.True(false, "autogenerated");
		}
		
	}
}
