using Xunit;

namespace TestProject
{
	public class Tracer	{
		[Fact]
		public void StartTrace()
		{
			Assert.True(false, "autogenerated");
		}
		
		[Fact]
		public void StopTrace()
		{
			Assert.True(false, "autogenerated");
		}
		
		[Fact]
		public void GetTraceResult()
		{
			Assert.True(false, "autogenerated");
		}
		
		[Fact]
		public void GetMethodAndClassName()
		{
			Assert.True(false, "autogenerated");
		}
		
	}
}
